### ISSUE TITLE
Swift 4.2 support.

### ISSUE THREAD

**Issue by Jain-Siddharth** [keshavvishwkarma/KVConstraintKit#1]
I am using your library on Xcode 10.1 with cocoa pod. Previously I was using Xcode 9.4 and it was working fine but I am getting so many error after Xcode update. It comes when I have used command pod repo update and then pod install. I am using swift 4.2 so might be issue with swift version but im not sure sure.

**Comment by keshavvishwkarma** [comment]
@Jain-Siddharth, Yes you are right, So for now you can set the `Swift Language Version - 4.0`.
Goto -> Target Build Setting -> then Search for `Swift Language Version` -> then change swift version.

**Comment by keshavvishwkarma** [comment]
🎉  Congrats & Thanks for your effort.

 🚀  KVConstraintKit (2.1) successfully published
 📅  March 5th, 19:34
 🌎  https://cocoapods.org/pods/KVConstraintKit
 👍  Tell your friends!
